version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ../confs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../app:/var/www/musich
    depends_on:
      - mysql
      - php

  php:
    build: 
      context: dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ../app:/var/www/musich
      - ../confs/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - ../envs/mysql.env
    volumes:
      - db_data:/var/lib/mysql

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ../app:/var/www/musich

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ../app:/var/www/musich
    entrypoint: ["php", "/var/www/musich/artisan"]

  vue:
    build:
      context: ./dockerfiles
      dockerfile: vue.dockerfile
    command: "npm run dev"
    volumes:
      - ../app:/var/www/musich
volumes:
  db_data:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450